# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae7c06972d23179bd718b9513ad453222a052ab407d7a58293d46f0966c70a4164aa95b7d1cd80ea854123c876543939e0c8bce9596cbfc8bc0450f8f5851df6

test:
  secret_key_base: 2eb2b8487a1d89dc72b17a73b1d33ca30f713e9cdcce47c1b7bfb2167623e0c4ad51b3ed481924296bf5334198c985cf83e640a8ffbdf8b0c91f3ad7289ad62b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
