# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/
//= require pace.min
//= require bootstrap.min
//= require jquery.validate.min
//= require jquery-validate.bootstrap-tooltip
//= require moment
//= require bootstrap-datetimepicker
//= require luna
//= require react
//= require react_ujs
//= require_tree ./components

getAge = (dateString) ->
  `var monthAge`
  `var dateAge`
  now = new Date
  today = new Date(now.getYear(), now.getMonth(), now.getDate())
  yearNow = now.getYear()
  monthNow = now.getMonth()
  dateNow = now.getDate()
  dob = new Date(dateString)
  yearDob = dob.getYear()
  monthDob = dob.getMonth()
  dateDob = dob.getDate()
  age = {}
  ageString = ''
  yearString = ''
  monthString = ''
  dayString = ''
  yearAge = yearNow - yearDob
  if monthNow >= monthDob
    monthAge = monthNow - monthDob
  else
    yearAge--
    monthAge = 12 + monthNow - monthDob
  if dateNow >= dateDob
    dateAge = dateNow - dateDob
  else
    monthAge--
    dateAge = 31 + dateNow - dateDob
    if monthAge < 0
      monthAge = 11
      yearAge--
  age =
    years: yearAge
    months: monthAge
    days: dateAge
  age

# ---
# generated by js2coffee 2.2.0